### ISSUE TITLE
Release into Foxy, Galactic, Humble, and Rolling

### ISSUE THREAD

**Issue by clalancette** [kobuki-base/velocity_smoother#19]
@stonier With the updates I've done in recent days, this package is in good shape for a release.  All of the tests pass on all of Foxy, Galactic, Humble, and Rolling, and the code uses most of our modern ROS 2 development practices.

There are 3 issues that we need to address to do a release here:
1.  `ecl_core` is not released into Humble.  Now, I know that `ecl_core` is having some problems building on Rolling, but `ecl_build`, which is the only package that `velocity_smoother` depends upon, is building fine.  So if you could do a release of `ecl_core` into Humble (even though we know it isn't going to totally work right now), that would unblock this.
2. The last time we released this package (into Eloquent), we used the release repository at https://github.com/stonier/velocity_smoother-release.git .  Our new best practices are to create a release repository under https://github.com/ros2-gbp.  Are you OK if I go ahead and create a release repository there?
3. The name of this package may be a little too generic.  When this was released into ROS 1, it was called `yocs_velocity_smoother`, which at least shows where it comes from.  But looking around https://github.com/ros/rosdistro, we also see a `velocity_smoother` from the COB set of packages, and also from navigation2.  My proposal is that we rename this package to something like `kobuki_velocity_smoother`, which should alleviate this concern.

Thoughts on the above?

**Comment by stonier** [comment]
1. Started looking into the release. The original problem was pretty simple, but it's since been complicated by some changes with Ubuntu that's causing some problems for Sophus, even foxy on `22.04.1` is failing. I'll need a bit longer to sort out. I do have a 22.04 environment in docker now at least.

2. Sure, go ahead.

3. I'm fine with the rename too.

**Comment by clalancette** [comment]
Sounds good.  I'll go ahead and rename the repository and the package within it to start with.  After that, I'll wait to create the release repository until we have the sophus stuff sorted.

**Comment by stonier** [comment]
So there goes 24hrs....and one particularly feisty refactor of what was originally a templatish work of art. GCC with it's proliferation of warnings has shot that down - turns out I was abusing std c++. Sadness.

Anyways, good to dive into a bit of c++ again. It's been a while.

Rolling - sophus + the ecl packages are on their way (should be on rosdistro as soon as bloom finishes with ecl_core now).
Humble - on their way, but going to take a bit longer as they block each other.

**Comment by stonier** [comment]
Rolling - ecl_core is up: https://github.com/ros/rosdistro/pull/34678

**Comment by clalancette** [comment]
> Rolling - ecl_core is up: [ros/rosdistro#34678](https://github.com/ros/rosdistro/pull/34678)

Excellent, thanks!  I may not have time to do this release today, but I'll get it moving in the next few days.

**Comment by clalancette** [comment]
https://github.com/ros2-gbp/ros2-gbp-github-org/pull/128 is the first step.

**Comment by clalancette** [comment]
All right, releases done in Rolling, Humble, Galactic, and Foxy.  Still waiting for the packages to build, but I'm going to close this out regardless.  Next up, I'll look at `cmd_vel_mux` (hopefully I'll have some time this weekend).
